services:
  web:
    image: parasti/nevertable:devel
    build:
      context: "."
      args:
        - "extra_extensions=xdebug"
    volumes:
      - ".:/var/www/html"
      - "./docker/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/vhost.conf:/etc/apache2/sites-enabled/000-default.conf"
    ports:
      - "127.0.0.1:80:80"
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway" # for xdebug
  db:
    image: mariadb:10.10.2
    volumes:
      - "./install:/docker-entrypoint-initdb.d"
      - "data_db:/var/lib/mysql"
    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8081:8080"
volumes:
  data_db: