services:
  web:
    image: php:5.6-apache
    build: "./build/web"
    volumes:
      - "..:/var/www/html"
      - "./logs/web:/var/log/apache2"
      - "./conf/php/php.ini:/usr/local/etc/php/php.ini"
      - "./conf/vhosts:/etc/apache2/sites-enabled"
    ports:
      - "127.0.0.1:8080:80"
  db:
    image: mariadb
    volumes:
      - "../install:/docker-entrypoint-initdb.d"
      - "data_db:/var/lib/mysql"
    environment:
      MARIADB_ROOT_HOST: localhost
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
  adminer:
    image: adminer
    ports:
      - "127.0.0.1:8081:8080"
volumes:
  data_db: